### ISSUE TITLE
tabs not on top bar 

### ISSUE THREAD

**Issue by red-co** [yoyurec/logseq-solarized-extended-theme#9]
screenshot
<img width="1280" alt="屏幕截图 2022-05-19 184121" src="https://user-images.githubusercontent.com/75922982/169277671-1a387f77-3da8-4654-8188-6de6ae9d473e.png">

Windows11
logseq 0.69 
solarized theme 1.82
tabs 1.13

**Comment by yoyurec** [comment]
did you restarted Logseq?
what about 1.8.3 theme version?

**Comment by yoyurec** [comment]
try new update 1.8.5!

**Comment by yoyurec** [comment]
@red-co  try latest 1.9.6

**Comment by red-co** [comment]
Thanks, but the 1.96 version of the tags still doesn't work . 
- for possible reasons, network related? Or unpacked plugin working? (I can't install plugins via marketplace.) ), (and I can't test whether these guesses are true, too), 
- and I'm sorry for bothering you,

**Comment by red-co** [comment]
I like the theme and even if tabs don't work, it's still great,

**Comment by yoyurec** [comment]
unpacked plugin maybe have securiti limits to work...

**Comment by yoyurec** [comment]
how do you install plugins? just load zip from release?

**Comment by red-co** [comment]
I threw it in, and this is the console.
```
"start refresh-tokens-loop"

index.3d9bdd88.js:2 #logseq-solarized-extended-theme [logseq-solarized-extended-theme] [Ready Error] DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at Wt.<anonymous> (lsp://logseq.io/logseq-solarized-extended-theme/dist/index.3d9bdd88.js:2:70614)
    at Wt.ready (lsp://logseq.io/logseq-solarized-extended-theme/dist/index.3d9bdd88.js:2:67116)
ready @ index.3d9bdd88.js:2
index.837f57ef.js:52 #tabs: MAIN
index.837f57ef.js:57 #tabs: MAIN DONE
index.837f57ef.js:41 DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at Pg (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:70627)
    at Og (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:70771)
    at Qg (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:52:6663)
    at ga (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:39:19092)
    at mp (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:44547)
    at dp (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:40206)
    at Am (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:40134)
    at Rl (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:39988)
    at js (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:36327)
    at ap (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:35275)
Ss @ index.837f57ef.js:41
index.837f57ef.js:41 Uncaught DOMException: Blocked a frame with origin "lsp://logseq.io" from accessing a cross-origin frame.
    at Pg (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:70627)
    at Og (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:70771)
    at Qg (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:52:6663)
    at ga (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:39:19092)
    at mp (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:44547)
    at dp (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:40206)
    at Am (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:40134)
    at Rl (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:39988)
    at js (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:36327)
    at ap (lsp://logseq.io/tabs/dist/assets/index.837f57ef.js:41:35275)
```
tabs will don't work , and the solarized theme will show some errors, (I've tried clearing the cache and reloading, or uninstalling logsq,)

**Comment by red-co** [comment]
It doesn't seem like a standard bug, and the actual impact isn't great, and I'm already embarrassed to bother you, so I turned off this issue

**Comment by yoyurec** [comment]
i think i have one last idea ))
on first screen error about security. you need to edit package.json to allow my theme(plugin) to do JS stuff...
moment, will push test release...

**Comment by yoyurec** [comment]
>  I'm already embarrassed to bother you
no problem )

**Comment by yoyurec** [comment]
try unpacked updated theme - https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v1.9.7
